# SITE CONFIGURATION
title: Path to OSCP 
author: Michael Nieto
description: > 
  My path to cyber security and the OSCP certification. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://michaelnieto.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Michael Nieto
  links:
    - https://twitter.com/mikensec
    - https://www.linkedin.com/in/nietomichael
    - https://github.com/mikensec
  
# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Sharing my path to OSCP and other IT related stuff.

hero_img: posts/modern_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: michaelnietotx@gmail.com # email for form submission

twitter_username: mikensec # replace with your_twitter_username or comment to remove link from footer
github_username:  mikensec # replace with your_github_username or comment to remove link from footer
#instagram_username:  # replace with your_instagram_username or comment to remove link from footer

disqus:
 shortname: mikensec # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-N8ZVQQW # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
