# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.define "ub1404" do |ub1404|
    ub1404.vm.box = "rapid7/metasploitable3-ub1404"
    ub1404.vm.hostname = "metasploitable3-ub1404"
    
    config.vm.provider "vmware_desktop" do |v|
     v.vmx["name"] = "UB1404"
     v.vmx["memsize"] = "1024"
     v.gui = true   
    end
    
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'

    ub1404.vm.network "private_network", type: "dhcp"
   
   end
end


